---
version: "3.8"

services:
  consul-server1:
    image: hashicorp/consul:1.15.2
    container_name: consul-server1
    restart: always
    volumes:
      - ./server1.hcl:/consul/config/server1.hcl
      - ./consul-acl.hcl:/consul/config/consul-acl.hcl
      - ./certs/:/consul/config/certs/
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.15.2
    container_name: consul-server2
    restart: always
    volumes:
      - ./server2.hcl:/consul/config/server2.hcl
      - ./consul-acl.hcl:/consul/config/consul-acl.hcl
      - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.15.2
    container_name: consul-server3
    restart: always
    volumes:
      - ./server3.hcl:/consul/config/server3.hcl
      - ./consul-acl.hcl:/consul/config/consul-acl.hcl
      - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.15.2
    container_name: consul-client
    restart: always
    volumes:
      - ./client.hcl:/consul/config/client.hcl
      - ./consul-acl.hcl:/consul/config/consul-acl.hcl
      - ./certs/:/consul/config/certs/
    networks:
      - consul
    command: "agent"

networks:
  consul:
    driver: bridge
